import { v7 as uuid } from 'uuid'
import dayjs from 'dayjs'
import type { StoredItem } from '$lib/types'

export const possibleItems = [
  {
    id: uuid(),
    name: 'milk',
    quantity: 1,
    dateAdded: dayjs().subtract(100, 'day'),
    shelfLife: 7,
  },
  {
    id: uuid(),
    name: 'eggs',
    quantity: 12,
    dateAdded: dayjs().subtract(16, 'day'),
    shelfLife: 35,
  },
  {
    id: uuid(),
    name: 'choy sum',
    quantity: 2,
    dateAdded: dayjs().subtract(12, 'day'),
    shelfLife: 5,
  },
  {
    id: uuid(),
    name: 'bananas',
    quantity: 6,
    dateAdded: dayjs().subtract(2, 'day'),
    shelfLife: 7,
  },
  {
    id: uuid(),
    name: 'apples',
    quantity: 4,
    dateAdded: dayjs().subtract(7, 'day'),
    shelfLife: 14,
  },
  {
    id: uuid(),
    name: 'tomatoes',
    quantity: 5,
    dateAdded: dayjs().subtract(2, 'day'),
    shelfLife: 7,
  },
  {
    id: uuid(),
    name: 'lettuce',
    quantity: 1,
    dateAdded: dayjs().subtract(4, 'day'),
    shelfLife: 7,
  },
  {
    id: uuid(),
    name: 'carrots',
    quantity: 8,
    dateAdded: dayjs().subtract(10, 'day'),
    shelfLife: 21,
  },
  {
    id: uuid(),
    name: 'broccoli',
    quantity: 2,
    dateAdded: dayjs().subtract(3, 'day'),
    shelfLife: 7,
  },
  {
    id: uuid(),
    name: 'cucumber',
    quantity: 3,
    dateAdded: dayjs().subtract(5, 'day'),
    shelfLife: 7,
  },
  {
    id: uuid(),
    name: 'strawberries',
    quantity: 1,
    dateAdded: dayjs().subtract(1, 'day'),
    shelfLife: 5,
  },
  {
    id: uuid(),
    name: 'potatoes',
    quantity: 6,
    dateAdded: dayjs().subtract(14, 'day'),
    shelfLife: 28,
  },
  {
    id: uuid(),
    name: 'onions',
    quantity: 4,
    dateAdded: dayjs().subtract(20, 'day'),
    shelfLife: 30,
  },
  {
    id: uuid(),
    name: 'bell peppers',
    quantity: 3,
    dateAdded: dayjs().subtract(4, 'day'),
    shelfLife: 7,
  },
  {
    id: uuid(),
    name: 'grapes',
    quantity: 1,
    dateAdded: dayjs().subtract(2, 'day'),
    shelfLife: 7,
  },
  {
    id: uuid(),
    name: 'avocados',
    quantity: 2,
    dateAdded: dayjs().subtract(1, 'day'),
    shelfLife: 5,
  },
  {
    id: uuid(),
    name: 'mushrooms',
    quantity: 8,
    dateAdded: dayjs().subtract(10, 'day'),
    shelfLife: 7,
  },
  {
    id: uuid(),
    name: 'zucchini',
    quantity: 2,
    dateAdded: dayjs().subtract(5, 'day'),
    shelfLife: 7,
  },
  {
    id: uuid(),
    name: 'oranges',
    quantity: 6,
    dateAdded: dayjs().subtract(8, 'day'),
    shelfLife: 14,
  },
  {
    id: uuid(),
    name: 'spinach',
    quantity: 1,
    dateAdded: dayjs().subtract(2, 'day'),
    shelfLife: 5,
  },
  {
    id: uuid(),
    name: 'lemons',
    quantity: 4,
    dateAdded: dayjs().subtract(10, 'day'),
    shelfLife: 21,
  },
  {
    id: uuid(),
    name: 'green beans',
    quantity: 1,
    dateAdded: dayjs().subtract(3, 'day'),
    shelfLife: 7,
  },
  {
    id: uuid(),
    name: 'cauliflower',
    quantity: 1,
    dateAdded: dayjs().subtract(4, 'day'),
    shelfLife: 7,
  },
] satisfies StoredItem[]
